# Assignment: Credit Card Fraud Detection revised

we return to the credit card use case (last time we used Random Forests).


## Pre-Stage
Use your pre-processing from the last assignment as input.


In [1]:
#download data
#get the data
!git clone https://github.com/keuperj/DATA.git

Cloning into 'DATA'...
remote: Enumerating objects: 126, done.
remote: Counting objects: 100% (39/39), done.
remote: Compressing objects: 100% (28/28), done.
remote: Total 126 (delta 11), reused 39 (delta 11), pack-reused 87
Receiving objects: 100% (126/126), 185.56 MiB | 13.67 MiB/s, done.
Resolving deltas: 100% (32/32), done.
Updating files: 100% (86/86), done.


In [3]:

!unzip DATA/creditcard.csv.zip


Archive:  DATA/creditcard.csv.zip
  inflating: creditcard.csv          


In [64]:
import pandas as pd
data = pd.read_csv("creditcard.csv")
len(data)

284807

In [5]:
from __future__ import absolute_import, division, print_function, unicode_literals

# TensorFlow and tf.keras
import tensorflow as tf
from tensorflow import keras

# Helper libraries
import numpy as np
import matplotlib.pyplot as plt

from sklearn.metrics import confusion_matrix


In [136]:
# your preprocessing code
data.fillna(0, inplace=True) #replace NaN with zeros
data.replace([np.inf, -np.inf], 0, inplace=True) #also replace of inf values

data2 = data.copy()
data2 = data2[len(data)//2:]

x_labels_train = data2["Class"]

data2.drop(columns = ["Class"])
X_train=data2.to_numpy(dtype='float') #data type float

data3 = data.copy()
data3 = data3[:len(data)//2]

x_labels_test = data3["Class"]

data3.drop(columns = ["Class"])
X_test=data3.to_numpy(dtype='float') #data type float

#normalize data
from sklearn.preprocessing import normalize
X_train=normalize(X_train, axis=0)#normalize each variable
X_test=normalize(X_test, axis=0)#normalize each variable


In [151]:
data4 = data.copy()
data4 = data4[len(data)//2:]

x_labels_train2 = data4["Class"]

data4.drop(columns = ["Class"])
X_train2=data4.to_numpy(dtype='float') #data type float

data5 = data.copy()
data5 = data5[:len(data)//2]

x_labels_test2 = data5["Class"]

data5.drop(columns = ["Class"])
X_test2=data5.to_numpy(dtype='float') #data type float

#normalize data
from sklearn.preprocessing import normalize
X_train2=normalize(X_train2, axis=0)#normalize each variable
X_test2=normalize(X_test2, axis=0)#normalize each variable

# Task: Train a MLP-Network
* Train and evaluate the model
* Compare the results to the Random Forrest
* Tune the hyper-parameters (like number of layers, neurons per layer, learning-rate and number of epochs ) to optimize the results

See: https://keras.io/api/

In [138]:
model = keras.Sequential([
    keras.layers.Dense(128, activation='relu'),
    keras.layers.Dense(128, activation='relu'),
    keras.layers.Dense(2, activation='softmax')
])

In [139]:
optimizer = keras.optimizers.Adam(learning_rate=0.001)
model.compile(optimizer=optimizer,
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [140]:
model.fit(X_train, x_labels_train, epochs=10)

Epoch 1/10
4451/4451 [==============================] - 17s 3ms/step - loss: 0.0052 - accuracy: 0.9996
Epoch 2/10
4451/4451 [==============================] - 14s 3ms/step - loss: 3.7439e-06 - accuracy: 1.0000
Epoch 3/10
4451/4451 [==============================] - 14s 3ms/step - loss: 2.0023e-07 - accuracy: 1.0000
Epoch 4/10
4451/4451 [==============================] - 14s 3ms/step - loss: 2.4576e-08 - accuracy: 1.0000
Epoch 5/10
4451/4451 [==============================] - 14s 3ms/step - loss: 2.6863e-09 - accuracy: 1.0000
Epoch 6/10
4451/4451 [==============================] - 14s 3ms/step - loss: 4.4883e-05 - accuracy: 1.0000
Epoch 7/10
4451/4451 [==============================] - 15s 3ms/step - loss: 2.2895e-09 - accuracy: 1.0000
Epoch 8/10
4451/4451 [==============================] - 14s 3ms/step - loss: 1.2013e-09 - accuracy: 1.0000
Epoch 9/10
4451/4451 [==============================] - 15s 3ms/step - loss: 8.5805e-10 - accuracy: 1.0000
Epoch 10/10
4451/4451 [==================

In [141]:
test_loss, test_acc = model.evaluate(X_test,  x_labels_test, verbose=2)

print('\nTest accuracy:', test_acc)

4451/4451 - 8s - loss: 6.1696e-04 - accuracy: 0.9998 - 8s/epoch - 2ms/step

Test accuracy: 0.9998103976249695


In [142]:
predictions = model.predict(X_test)
predictions

4451/4451 [==============================] - 8s 2ms/step


array([[1.00000000e+00, 1.08705885e-10],
       [1.00000000e+00, 1.20446306e-10],
       [1.00000000e+00, 7.55481025e-11],
       ...,
       [1.00000000e+00, 1.08395737e-10],
       [1.00000000e+00, 8.65831296e-11],
       [1.00000000e+00, 5.98579311e-11]], dtype=float32)

In [143]:
i = 2
np.argmax(predictions[i])

0

In [144]:
x_labels_test[i]

0

In [145]:
single_values = []

for value in predictions:
  single_values.append(np.argmax(value))

confusion_matrix(x_labels_test, single_values)

array([[142107,     27],
       [     0,    269]])

RF

In [165]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(n_estimators=30)
rf.fit(X_train2, x_labels_train2)
predictions_rf = rf.predict(X_test2)

In [166]:
confusion_matrix(x_labels_test2, predictions_rf)

array([[142111,     23],
       [     0,    269]])