# Assignment I: Numpy

Perform the follwing tasks:


In [2]:
#1: import the numpy library
import numpy as np

In [16]:
#2: create a random 10x10 array named A
A = np.random.rand(10,10)
A

array([[0.57657299, 0.46634108, 0.21734567, 0.50229537, 0.05574679,
        0.56356893, 0.51513741, 0.25910086, 0.25228149, 0.77347071],
       [0.97380975, 0.75509046, 0.601464  , 0.21346513, 0.92075743,
        0.50832761, 0.45918159, 0.34313589, 0.56034732, 0.19598645],
       [0.88193782, 0.69243272, 0.26448837, 0.63094177, 0.45320664,
        0.41822484, 0.21043658, 0.97306693, 0.05279548, 0.42812164],
       [0.11158198, 0.17257135, 0.26938241, 0.04763437, 0.70015414,
        0.1806943 , 0.84530492, 0.61312781, 0.93421029, 0.97345539],
       [0.54373855, 0.79672002, 0.83769855, 0.06348369, 0.45264039,
        0.18952575, 0.2452743 , 0.39652766, 0.97432687, 0.83057455],
       [0.51891834, 0.04389347, 0.35531303, 0.84927554, 0.4911943 ,
        0.58842454, 0.6915549 , 0.45957526, 0.29213787, 0.35460477],
       [0.57176244, 0.54889277, 0.55092733, 0.12377731, 0.5395894 ,
        0.64396019, 0.93028292, 0.20848342, 0.31770203, 0.21686787],
       [0.13047783, 0.79110944, 0.1921122

In [17]:
#3: return only the odd rows of A
A[::2]

array([[0.57657299, 0.46634108, 0.21734567, 0.50229537, 0.05574679,
        0.56356893, 0.51513741, 0.25910086, 0.25228149, 0.77347071],
       [0.88193782, 0.69243272, 0.26448837, 0.63094177, 0.45320664,
        0.41822484, 0.21043658, 0.97306693, 0.05279548, 0.42812164],
       [0.54373855, 0.79672002, 0.83769855, 0.06348369, 0.45264039,
        0.18952575, 0.2452743 , 0.39652766, 0.97432687, 0.83057455],
       [0.57176244, 0.54889277, 0.55092733, 0.12377731, 0.5395894 ,
        0.64396019, 0.93028292, 0.20848342, 0.31770203, 0.21686787],
       [0.41171393, 0.65006281, 0.21096019, 0.73593624, 0.75219877,
        0.68598791, 0.68560565, 0.90676953, 0.71912686, 0.3817047 ]])

In [9]:
#4: perform a matrix multiplication of A with it's transposed
A * A.transpose()

array([[9.18147390e-01, 7.66587562e-01, 1.24937067e-01, 1.44657032e-01,
        2.55900527e-01, 7.03973587e-01, 1.52963521e-01, 4.59884701e-01,
        3.68864665e-01, 2.03715109e-01],
       [7.66587562e-01, 5.49290376e-01, 9.56796447e-02, 3.92710128e-02,
        2.65417474e-02, 1.72282874e-01, 1.74827858e-02, 4.20819632e-01,
        2.69079729e-01, 4.75025845e-02],
       [1.24937067e-01, 9.56796447e-02, 6.38474620e-01, 7.16469907e-03,
        1.26064819e-02, 5.03103392e-02, 3.24060215e-03, 5.83225703e-02,
        2.33749782e-01, 3.40047310e-01],
       [1.44657032e-01, 3.92710128e-02, 7.16469907e-03, 9.45589973e-01,
        3.90191327e-01, 7.21813930e-01, 2.63575494e-01, 3.21507214e-01,
        1.77309338e-01, 9.09689932e-02],
       [2.55900527e-01, 2.65417474e-02, 1.26064819e-02, 3.90191327e-01,
        1.75613880e-01, 5.84407458e-01, 3.35755236e-04, 8.37057092e-02,
        3.36978961e-01, 5.02862989e-01],
       [7.03973587e-01, 1.72282874e-01, 5.03103392e-02, 7.21813930e-01,
   

In [11]:
#5: compute the matrix inverse of A
np.linalg.inv(A)

array([[-0.68769723,  0.51207302,  0.13110539, -1.3172886 , -0.49691095,
         1.49581598,  0.25747283, -0.02553643,  0.22455608,  0.05267023],
       [ 0.56533942, -0.95972374,  0.9743061 , -0.338636  , -0.21855623,
        -0.05298728, -1.29823272,  1.11109557,  0.14950324,  0.06024869],
       [ 0.38345363, -1.70452616, -0.31699151, -0.48550645,  0.89916378,
        -0.52812921, -0.19748832,  0.18282215,  1.7323369 , -0.46830072],
       [ 1.04281599, -0.40906237, -1.31004451,  0.68514492,  0.68684649,
        -0.73413704,  0.36102119, -0.38122977,  0.78475359, -1.19257668],
       [ 0.51564977, -2.32806284, -0.04392507, -0.81469672,  0.45990105,
         0.81427211, -0.98537181,  0.62829326,  0.82703324,  0.45300486],
       [ 0.5266257 ,  2.24343179,  0.11688453,  1.90863263, -0.6143253 ,
        -1.16394645,  0.24523824, -1.6574284 , -0.9973767 ,  0.1306028 ],
       [-1.16579922,  0.63441436,  0.4039237 , -0.15307871, -0.78929909,
         0.42241335,  0.11973871,  0.74592674

In [18]:
#6: divide all entries of A which are lager than 0.5 by 2 (hint: use where() )
np.where(A>0.5, A/2, A)

array([[0.28828649, 0.46634108, 0.21734567, 0.25114769, 0.05574679,
        0.28178446, 0.25756871, 0.25910086, 0.25228149, 0.38673536],
       [0.48690487, 0.37754523, 0.300732  , 0.21346513, 0.46037872,
        0.2541638 , 0.45918159, 0.34313589, 0.28017366, 0.19598645],
       [0.44096891, 0.34621636, 0.26448837, 0.31547088, 0.45320664,
        0.41822484, 0.21043658, 0.48653347, 0.05279548, 0.42812164],
       [0.11158198, 0.17257135, 0.26938241, 0.04763437, 0.35007707,
        0.1806943 , 0.42265246, 0.3065639 , 0.46710515, 0.48672769],
       [0.27186927, 0.39836001, 0.41884928, 0.06348369, 0.45264039,
        0.18952575, 0.2452743 , 0.39652766, 0.48716343, 0.41528728],
       [0.25945917, 0.04389347, 0.35531303, 0.42463777, 0.4911943 ,
        0.29421227, 0.34577745, 0.45957526, 0.29213787, 0.35460477],
       [0.28588122, 0.27444638, 0.27546366, 0.12377731, 0.2697947 ,
        0.32198009, 0.46514146, 0.20848342, 0.31770203, 0.21686787],
       [0.13047783, 0.39555472, 0.1921122

In [22]:
#7: compute the singular value decomposition of A
B = np.linalg.svd(A)
#7.1: plot the singular values
%matplotlib inline
import matplotlib.pyplot as plt


#7.2: reconstruct A' by using only the top 5 singular values