# Assignment I: Numpy

Perform the follwing tasks:


In [1]:
#1: import the numpy library
import numpy as np

In [2]:
#2: create a random 10x10 array named A
A = np.random.rand(10,10)
A

array([[0.1579624 , 0.63100678, 0.35839596, 0.68733351, 0.46991288,
        0.14721725, 0.5462504 , 0.07131606, 0.67090739, 0.39246141],
       [0.63027945, 0.33804332, 0.63493128, 0.15052833, 0.58468071,
        0.13598999, 0.05256528, 0.38004107, 0.7787013 , 0.0354103 ],
       [0.38676502, 0.49033338, 0.05219415, 0.01341489, 0.29892015,
        0.74404435, 0.73566956, 0.00411569, 0.36658229, 0.78291049],
       [0.07011605, 0.72264615, 0.51290965, 0.50628981, 0.55788058,
        0.61538692, 0.25497001, 0.35695927, 0.1081343 , 0.28696831],
       [0.0564141 , 0.50143519, 0.98609457, 0.74348931, 0.45635963,
        0.85468947, 0.338295  , 0.0238206 , 0.19402111, 0.44916537],
       [0.99320849, 0.66771283, 0.17791921, 0.25787827, 0.7285853 ,
        0.9909962 , 0.84120406, 0.18540924, 0.63049699, 0.32721217],
       [0.69843113, 0.14541634, 0.36484286, 0.65257939, 0.83159631,
        0.72326751, 0.36132549, 0.35389051, 0.72964382, 0.89852618],
       [0.59218418, 0.22108438, 0.7468180

In [ ]:
#3: return only the odd rows of A
A[1::2]

array([[0.97380975, 0.75509046, 0.601464  , 0.21346513, 0.92075743,
        0.50832761, 0.45918159, 0.34313589, 0.56034732, 0.19598645],
       [0.11158198, 0.17257135, 0.26938241, 0.04763437, 0.70015414,
        0.1806943 , 0.84530492, 0.61312781, 0.93421029, 0.97345539],
       [0.51891834, 0.04389347, 0.35531303, 0.84927554, 0.4911943 ,
        0.58842454, 0.6915549 , 0.45957526, 0.29213787, 0.35460477],
       [0.13047783, 0.79110944, 0.19211221, 0.61480893, 0.26575441,
        0.84123571, 0.30208733, 0.49769452, 0.64855299, 0.19485219],
       [0.86559265, 0.81077546, 0.2796267 , 0.1302275 , 0.49034156,
        0.04993269, 0.20148613, 0.56386114, 0.87804387, 0.12411826]])

In [3]:
#4: perform a matrix multiplication of A with it's transposed
np.dot(A, A.transpose())

array([[2.17410589, 1.53080759, 1.60378551, 1.70154234, 2.02297488,
        2.33165211, 2.34341026, 2.18314372, 2.01397403, 1.56601876],
       [1.53080759, 2.05249072, 1.07405443, 1.34364793, 1.51996079,
        2.18149131, 2.15729888, 1.76665213, 1.29453388, 1.16419995],
       [1.60378551, 1.07405443, 2.32443149, 1.493009  , 1.77322591,
        2.78633807, 2.39416489, 1.91858454, 1.70189906, 1.93715454],
       [1.70154234, 1.34364793, 1.493009  , 2.02294466, 2.27370774,
        2.23303048, 2.13580202, 1.9390629 , 1.60297547, 1.41164606],
       [2.02297488, 1.51996079, 1.77322591, 2.27370774, 3.07294149,
        2.49580528, 2.63076734, 2.67277501, 1.71642019, 1.55519723],
       [2.33165211, 2.18149131, 2.78633807, 2.23303048, 2.49580528,
        4.28996509, 3.47023685, 3.05992177, 2.262824  , 2.73095784],
       [2.34341026, 2.15729888, 2.39416489, 2.13580202, 2.63076734,
        3.47023685, 3.87811445, 2.80942586, 2.22446817, 2.01731034],
       [2.18314372, 1.76665213, 1.9185845

In [ ]:
#5: compute the matrix inverse of A
np.linalg.inv(A)

array([[-0.68769723,  0.51207302,  0.13110539, -1.3172886 , -0.49691095,
         1.49581598,  0.25747283, -0.02553643,  0.22455608,  0.05267023],
       [ 0.56533942, -0.95972374,  0.9743061 , -0.338636  , -0.21855623,
        -0.05298728, -1.29823272,  1.11109557,  0.14950324,  0.06024869],
       [ 0.38345363, -1.70452616, -0.31699151, -0.48550645,  0.89916378,
        -0.52812921, -0.19748832,  0.18282215,  1.7323369 , -0.46830072],
       [ 1.04281599, -0.40906237, -1.31004451,  0.68514492,  0.68684649,
        -0.73413704,  0.36102119, -0.38122977,  0.78475359, -1.19257668],
       [ 0.51564977, -2.32806284, -0.04392507, -0.81469672,  0.45990105,
         0.81427211, -0.98537181,  0.62829326,  0.82703324,  0.45300486],
       [ 0.5266257 ,  2.24343179,  0.11688453,  1.90863263, -0.6143253 ,
        -1.16394645,  0.24523824, -1.6574284 , -0.9973767 ,  0.1306028 ],
       [-1.16579922,  0.63441436,  0.4039237 , -0.15307871, -0.78929909,
         0.42241335,  0.11973871,  0.74592674

In [ ]:
#6: divide all entries of A which are lager than 0.5 by 2 (hint: use where() )
np.where(A>0.5, A/2, A)

array([[0.28828649, 0.46634108, 0.21734567, 0.25114769, 0.05574679,
        0.28178446, 0.25756871, 0.25910086, 0.25228149, 0.38673536],
       [0.48690487, 0.37754523, 0.300732  , 0.21346513, 0.46037872,
        0.2541638 , 0.45918159, 0.34313589, 0.28017366, 0.19598645],
       [0.44096891, 0.34621636, 0.26448837, 0.31547088, 0.45320664,
        0.41822484, 0.21043658, 0.48653347, 0.05279548, 0.42812164],
       [0.11158198, 0.17257135, 0.26938241, 0.04763437, 0.35007707,
        0.1806943 , 0.42265246, 0.3065639 , 0.46710515, 0.48672769],
       [0.27186927, 0.39836001, 0.41884928, 0.06348369, 0.45264039,
        0.18952575, 0.2452743 , 0.39652766, 0.48716343, 0.41528728],
       [0.25945917, 0.04389347, 0.35531303, 0.42463777, 0.4911943 ,
        0.29421227, 0.34577745, 0.45957526, 0.29213787, 0.35460477],
       [0.28588122, 0.27444638, 0.27546366, 0.12377731, 0.2697947 ,
        0.32198009, 0.46514146, 0.20848342, 0.31770203, 0.21686787],
       [0.13047783, 0.39555472, 0.1921122

In [ ]:
#7: compute the singular value decomposition of A
U,S,V = np.linalg.svd(A)
#7.1: plot the singular values
print(U)
print(S)
print(V)

#7.2: reconstruct A' by using only the top 5 singular values

[[-0.27908818  0.39901077 -0.09816827  0.12132913 -0.24201732 -0.37552491
   0.25957004 -0.0076414   0.31127575 -0.61206494]
 [-0.24921295  0.05336232 -0.72856755 -0.13438572  0.1629536   0.2847258
  -0.19323076 -0.44542199 -0.14296663 -0.14958003]
 [-0.34406635 -0.11360182  0.1244769  -0.0876225  -0.29617717  0.44869361
   0.5047208  -0.26099702  0.38047117  0.29811585]
 [-0.32879373 -0.1780201   0.24999284  0.20669463 -0.62301792  0.02091545
  -0.44824732 -0.183855   -0.34956657 -0.09731677]
 [-0.23184661  0.24291005  0.4412544   0.00599233  0.41060485  0.14052524
   0.32612146 -0.22148842 -0.55697415 -0.19627603]
 [-0.32574146 -0.36642518  0.13902538 -0.18755164  0.30072526 -0.61880306
  -0.094983   -0.39586176  0.190507    0.17247401]
 [-0.29905175 -0.33879364  0.16101582 -0.44374908  0.17192431  0.29466756
  -0.1988072   0.43073028  0.17135218 -0.4496067 ]
 [-0.40621855  0.26970949  0.07600159  0.55985021  0.35109286  0.16577628
  -0.34571044  0.1789746   0.30120379  0.22364139]
 