# Assignment I: Numpy

Perform the follwing tasks:


In [2]:
#1: import the numpy library
import numpy as np

In [3]:
#2: create a random 10x10 array named A
A = np.random.rand(10,10)
A

In [8]:
#3: return only the odd rows of A
A[::2]

array([[0.95820008, 0.87713672, 0.21846383, 0.70511664, 0.41152989,
        0.76830447, 0.29160125, 0.98925405, 0.41433682, 0.48755506],
       [0.57188902, 0.44775438, 0.79904607, 0.02540717, 0.03222875,
        0.61430202, 0.0054626 , 0.66500427, 0.24915164, 0.98347843],
       [0.62182732, 0.45163833, 0.39115641, 0.58176784, 0.4190631 ,
        0.7171827 , 0.00944035, 0.86379598, 0.93612344, 0.77841849],
       [0.52456401, 0.04038275, 0.59323441, 0.3478876 , 0.03556599,
        0.29620955, 0.44883897, 0.94226045, 0.13568614, 0.85776638],
       [0.89025316, 0.45418701, 0.93818281, 0.74080336, 0.35997278,
        0.90093967, 0.8545987 , 0.45817025, 0.32412988, 0.50828127]])

In [9]:
#4: perform a matrix multiplication of A with it's transposed
A * A.transpose()

array([[9.18147390e-01, 7.66587562e-01, 1.24937067e-01, 1.44657032e-01,
        2.55900527e-01, 7.03973587e-01, 1.52963521e-01, 4.59884701e-01,
        3.68864665e-01, 2.03715109e-01],
       [7.66587562e-01, 5.49290376e-01, 9.56796447e-02, 3.92710128e-02,
        2.65417474e-02, 1.72282874e-01, 1.74827858e-02, 4.20819632e-01,
        2.69079729e-01, 4.75025845e-02],
       [1.24937067e-01, 9.56796447e-02, 6.38474620e-01, 7.16469907e-03,
        1.26064819e-02, 5.03103392e-02, 3.24060215e-03, 5.83225703e-02,
        2.33749782e-01, 3.40047310e-01],
       [1.44657032e-01, 3.92710128e-02, 7.16469907e-03, 9.45589973e-01,
        3.90191327e-01, 7.21813930e-01, 2.63575494e-01, 3.21507214e-01,
        1.77309338e-01, 9.09689932e-02],
       [2.55900527e-01, 2.65417474e-02, 1.26064819e-02, 3.90191327e-01,
        1.75613880e-01, 5.84407458e-01, 3.35755236e-04, 8.37057092e-02,
        3.36978961e-01, 5.02862989e-01],
       [7.03973587e-01, 1.72282874e-01, 5.03103392e-02, 7.21813930e-01,
   

In [11]:
#5: compute the matrix inverse of A
np.linalg.inv(A)

array([[-0.68769723,  0.51207302,  0.13110539, -1.3172886 , -0.49691095,
         1.49581598,  0.25747283, -0.02553643,  0.22455608,  0.05267023],
       [ 0.56533942, -0.95972374,  0.9743061 , -0.338636  , -0.21855623,
        -0.05298728, -1.29823272,  1.11109557,  0.14950324,  0.06024869],
       [ 0.38345363, -1.70452616, -0.31699151, -0.48550645,  0.89916378,
        -0.52812921, -0.19748832,  0.18282215,  1.7323369 , -0.46830072],
       [ 1.04281599, -0.40906237, -1.31004451,  0.68514492,  0.68684649,
        -0.73413704,  0.36102119, -0.38122977,  0.78475359, -1.19257668],
       [ 0.51564977, -2.32806284, -0.04392507, -0.81469672,  0.45990105,
         0.81427211, -0.98537181,  0.62829326,  0.82703324,  0.45300486],
       [ 0.5266257 ,  2.24343179,  0.11688453,  1.90863263, -0.6143253 ,
        -1.16394645,  0.24523824, -1.6574284 , -0.9973767 ,  0.1306028 ],
       [-1.16579922,  0.63441436,  0.4039237 , -0.15307871, -0.78929909,
         0.42241335,  0.11973871,  0.74592674

In [13]:
#6: divide all entries of A which are lager than 0.5 by 2 (hint: use where() )

IndexError: ignored

In [ ]:
#7: compute the singular value decomposition of A
#7.1: plot the singular values
#7.2: reconstruct A' by using only the top 5 singular values